spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabase?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: java
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect